### PR TITLE
Fix posthtml plugin name

### PR DESCRIPTION
**Pull request by voischev**

### CODE REVIEW

**Comment by jonathantneal** [comment]
Thanks for this pull and your issue! I hope people find this plugin useful.

I like the idea of wrapping the logo in a link, but (I’m curious) why I would need to name the plugin function? It doesn’t seem to add much clarity or value the plugin (maybe just my opinion).

**Comment by voischev** [comment]
Fuction name used in this code https://github.com/posthtml/posthtml/blob/master/lib/posthtml.js#L46 :)

What are my next steps with this PR?

**Comment by jonathantneal** [comment]
Thanks for the explanation. I will merge this shortly. I may make one change and use `Object.defineProperty` to set the name as `posthtml-inline-assets` so the message is clearer.

**Comment by voischev** [comment]
Cool!

**Comment by jonathantneal** [comment]
Okay, just a little bit long. I cannot rename the plugin the way I wanted to. http://stackoverflow.com/questions/31977822/can-function-names-be-configured-in-node-js/31978235#31978235

**Comment by jonathantneal** [comment]
I merged this in the command line, so it looks like I didn’t accept it, but I did! https://github.com/jonathantneal/posthtml-inline-assets/commit/78641b01fc3923ab07584a382d7ef441184e80d4

**Pull request closed without merging**
